### PR TITLE
added czech translate

### PR DESCRIPTION
**Pull request by kierwin1987**
**Describe Pull request**
Added czech locale to folder locales

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by i-kulgu — CHANGES_REQUESTED** [review]
Can you update your translation and add the auto switcher code into it please.

**Comment by kierwin1987** [comment]
I think it could be done.

**Review by i-kulgu — APPROVED** [review]
LGTM

**Review by zdenda142 — COMMENTED** [review]
Nice translate

**Pull request closed without merging**
